# provide s3 configuration
[s3]
access_key_id = "0000000000000000000000000"
bucket = "bucket_name"
endpoint = "endpoint_name"
region = "region_name"
secret_access_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# backup task configuration
[[backup]]
exclude = ["./some_path", "./another/path"]   # exclude path (relative path to the `path` in this section)
interval = 86400                              # run backup every n seconds
keep = 5                                      # keep n backups (default: 5)
name = "backup_task_1"                        # backup name (should be unique between tasks)
path = "/backup/path"                         # location (see volume in docker-compose.yml)

# another task
[[backup]]
exclude = ["path", "to", "exclude"]
interval = 43200
name = "backup_task_2"
path = "/backup/path"

# ...
